### ISSUE TITLE
Can't authenticate with UniFi console 8.1.113

### ISSUE THREAD

**Issue by pizzalorddex** [darnfish/homebridge-unifi-wap-light#2]
**Describe The Bug:**
When starting the plugin it cannot authenticate with the UniFi console API. The error "AxiosError: Request failed with status code 401" is reported. It looks like the API endpoint login may have been changed from "https://host:8443/api/auth/login" to "https://host:8443/api/login". More than this may have been changed with the API.

I ran `curl -k -X POST https://host:8443/api/auth/login -H "Content-Type: application/json" -d '{"username":"myUsername","password":"myPassword"}'` and got the response `{"meta":{"rc":"error","msg":"api.err.LoginRequired"},"data":[]}`

I ran `curl -k -X POST https://host:8443/api/login -H "Content-Type: application/json" -d '{"username":"myUsername","password":"myPassword"}'` and got the response `{"meta":{"rc":"ok"},"data":[]}`

**To Reproduce:**
Run UniFi Console version 8.1.113 or newer
Install plugin with Homebridge and configure according to documentation
Run plugin

**Expected behavior:**
The plugin is able to log in via the API

**Logs:**

```
[4/9/2024, 8:14:27 PM] Homebridge v1.7.0 (HAP v0.11.1) (UniFi WAP Lights) is running on port 32624.

/var/lib/homebridge/node_modules/homebridge-unifi-wap-light/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 401
    at settle (/var/lib/homebridge/node_modules/homebridge-unifi-wap-light/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-unifi-wap-light/node_modules/axios/lib/adapters/http.js:589:11)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/var/lib/homebridge/node_modules/homebridge-unifi-wap-light/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UnifiWAPLight.auth (/var/lib/homebridge/node_modules/homebridge-unifi-wap-light/src/platform.ts:73:23)
    at UnifiWAPLight.discoverDevices (/var/lib/homebridge/node_modules/homebridge-unifi-wap-light/src/platform.ts:105:3)
```

**Plugin Config:**

```json
{
    "name": "UniFi WAP Lights",
    "host": "hostname:8443",
    "username": "HomebridgeUser",
    "password": "AGoodPassword",
    "_bridge": {
        "username": "ChildBridgeMAC",
        "port": 32624
    },
    "platform": "UnifiWAPLight"
}
```

**Environment:**

* **Plugin Version**: v1.1.3
* **Homebridge Version**: v1.7.0
* **Node.js Version**: v20.12.1
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by pizzalorddex** [comment]
Just as info to others:

I want to clarify that the API endpoint was not changed. Self-hosted consoles and UniFi OS consoles use different API endpoints for authentication and other calls. 

In this sense, this is not really a bug, but by design. This plugin was most likely developed with a UniFi OS based console environment.

I created a fork which introduces support for both API types and I have continued to develop my fork. My pull request to merge changes was seen after some time, but no approval was made.

I am closing this as this defect is by design.
